### ISSUE TITLE
初始密码问题

### ISSUE THREAD

**Issue by chenglinjava68** [Gyv12345/yt4j-boot#2]
初始密码好像不是
admin
123456

**Comment by Gyv12345** [comment]
你看我已经部署的预览项目，用这个就能登录

**Comment by chenglinjava68** [comment]
![image](https://user-images.githubusercontent.com/12620529/100312664-e0311600-2fed-11eb-87a8-d388e0e49de3.png)
试了 不行

**Comment by chenglinjava68** [comment]
==>  Preparing: SELECT id,dept_id,nick_name,username,password,id_card,avatar,sex,email,phone,state,create_time,update_time FROM sys_user WHERE (username = ?)
==> Parameters: admin(String)
<==    Columns: id, dept_id, nick_name, username, password, id_card, avatar, sex, email, phone, state, create_time, update_time
<==        Row: 1, 1, 超级管理员, admin, $2a$10$ctfu9KkAOkfR9vNcl41PSOKu6LP0d03pvQmARBhmUNPLBtdkKzK3S, 410303198911282511, https://s1.ax1x.com/2020/08/14/dCRXDg.jpg, 1, gyv12345@163.com, 15139960649, 1, 2020-08-11 13:42:53, 2020-08-19 16:15:01
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@72e6d05e]
dtopass//YY92TFZRLL+vU4iNGjw0kyY1D6H/weESCVhr11B1FCzH2d2X2YOZ1Wsa5qYZhI7ub4ZXgKsaJhICb9GsHN5h5y9HMPsT0Qyx88J/pduWsigwnWKowJ2vZYD285Es8oxoCYXNovFGBIO36kdWQGzL64IDv/zhf+TuOElJZo4VT2E=
userpass//YY92TFZRLL+vU4iNGjw0kyY1D6H/weESCVhr11B1FCzH2d2X2YOZ1Wsa5qYZhI7ub4ZXgKsaJhICb9GsHN5h5y9HMPsT0Qyx88J/pduWsigwnWKowJ2vZYD285Es8oxoCYXNovFGBIO36kdWQGzL64IDv/zhf+TuOElJZo4VT2E=
2020-11-26 13:46:28.509 ERROR 17644 --- [nio-9999-exec-2] c.y.w.h.GlobalExceptionHandlerResolver   : 全局异常信息 ex=用户名或密码错误

org.springframework.security.authentication.BadCredentialsException: 用户名或密码错误
	at cn.yt4j.sys.service.impl.SysUserServiceImpl.login(SysUserServiceImpl.java:88) ~[classes/:na]
	at cn.yt4j.sys.service.impl.SysUserServiceImpl$$FastClassBySpringCGLIB$$cff30837.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at cn.yt4j.sys.service.impl.SysUserServiceImpl$$EnhancerBySpringCGLIB$$9fffc2ec.login(<generated>) ~[classes/:na]
	at cn.yt4j.sys.controller.SysUserController.login(SysUserController.java:45) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.37.jar:9.0.37]

**Comment by Gyv12345** [comment]
我增加了rsa加密，你通过前台应该是可以进去的
![Uploading image.png…]()

**Comment by Gyv12345** [comment]
我切换到本地环境，去除rsa在swagger里试了一下，没问题啊
